Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Models/Device.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DeviceMvcWeb.Models
{
    public class Device
    {
        [HiddenInput(DisplayValue = false)]
        public Guid DeviceID { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string DeviceName { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string DeDetailUrl { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string Type1 { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string Type2 { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string Type3 { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string Brand { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string Tag { get; set; }

    }
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Models/DeviceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeviceMvcWeb.Models
{
    public class DeviceModel
    {
        public IEnumerable<Device> Products { get; set; }
    }
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Models/EFDbContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DeviceMvcWeb.Models
{
    public class EFDbContext : DbContext
    {
        public DbSet<Device> Device { get; set; }
    }
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DeviceMvcWeb.Models
{
    public class Product
    {
        [HiddenInput(DisplayValue = false)]
        public int ProductID { get; set; }
        [Required(ErrorMessage = "Please enter a product name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required]
        [Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive price")]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Please specify a category")]
        public string Category { get; set; }
    }
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeviceMvcWeb.Models;

namespace DeviceMvcWeb.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View(new EFDbContext().Device.ToList());
        }


        [HttpGet]
        public ActionResult Create()
        {
            //var a = new EFDbContext();
            //device.DeviceID = Guid.NewGuid();
            //a.Device.Add(device);
            //a.SaveChanges();
            return View();
        }

        public ActionResult Create(Device device)
        {
            var a = new EFDbContext();
            device.DeviceID = Guid.NewGuid();
            a.Device.Add(device);
            a.SaveChanges();
            return View();
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var a = new EFDbContext();
            var temp = a.Device.SingleOrDefault(c => c.DeviceID == id);
            a.Device.Remove(temp);
            a.SaveChanges();
            return View("Index", new EFDbContext().Device.ToList());
        }


    }
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Controllers/DeviceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DeviceMvcWeb.Models;

namespace DeviceMvcWeb.Controllers
{
    public class DeviceController : Controller
    {
        //
        // GET: /Device/

        public ActionResult About()
        {
            ViewBag.AboutClass = "open";
            return View();
        }

        public ActionResult Index()
        {
            ViewBag.IndexClass = "open";
            return View();
        }

        public ActionResult Product()
        {
            ViewBag.ProductClass = "open";
            DeviceModel viewModel = new DeviceModel();
            viewModel.Products = new EFDbContext().Device.ToList();
            return View("Product", viewModel);
        }

        public ActionResult Search(string content)
        {
            return View();
        }

    }
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Admin/Create.cshtml
@model DeviceMvcWeb.Models.Device

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>Device</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.DeviceName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DeviceName)
                @Html.ValidationMessageFor(model => model.DeviceName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.DeDetailUrl)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.DeDetailUrl)
                @Html.ValidationMessageFor(model => model.DeDetailUrl)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type1)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type1)
                @Html.ValidationMessageFor(model => model.Type1)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type2)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type2)
                @Html.ValidationMessageFor(model => model.Type2)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type3)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type3)
                @Html.ValidationMessageFor(model => model.Type3)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Brand)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Brand)
                @Html.ValidationMessageFor(model => model.Brand)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Tag)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Tag)
                @Html.ValidationMessageFor(model => model.Tag)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Admin/Index.cshtml
@model IEnumerable<DeviceMvcWeb.Models.Device>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DeviceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeDetailUrl)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Brand)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tag)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DeviceName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeDetailUrl)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type2)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tag)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.DeviceID }) |
                @Html.ActionLink("Details", "Details", new { id=item.DeviceID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.DeviceID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Device/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>关于我们</h2>
<div class="pro">
    <div style="float: right; width: 580px;">
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;南京名炽行数码科技有限公司主要经营现代办公设备、品牌电脑、会议设备、办公文具等高科技产品，并提供专业化的维修售后服务，是一家产品、技术、服务配备齐全的专业化公司。<br>
            &nbsp;&nbsp;&nbsp;&nbsp;本公司经营的办公产品实行多样化经营，一切以客户需求为中心。专业的办公应用方案设计；专业的方案实施；专业的售后服务。客户需求及行业专业性双元素的结合，为客户轻松、高效、经济的实现各类办公应用。<br>
            &nbsp;&nbsp;&nbsp;&nbsp;南京名炽行数码科技有限公司将与各企事业单位融为一体，成为大家的IT部、咨询部、网络部……
        </p>
    </div>
    <img src="~/img/pic001.jpg" width="300" height="160">
</div>
<div style="clear: both;"></div>
<div class="arc content">
    <h2>联系我们</h2>
    <div class="pro">
        <img src="~/img/map01.jpg" width="300" height="159" style="float: right; width: 300px;">
        <div>
            <p>公司地址：南京市玄武区珠江路688号1-01幢280室</p>
            <p>公司邮箱：njmcxsm@126.com</p>
            <p>联系人：王先生 </p>
            <p>联系方式：18105180604</p>
        </div>
        <div style="clear: both; padding-bottom: 20px;"></div>
    </div>

</div>

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Device/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.ActionLink("更多", "Product", "Device")产品介绍</h2>
<div class="pro">
    <ul>
        <li>
            <img src="~/img/p01.jpg" alt="">
            <h4>打印机</h4>
            <p>· 喷墨打印机</p>
            <p>· 激光打印机</p>
            <p>· 针式打印机</p>
            <p>· 多功能一体机</p>
        </li>
        <li>
            <img src="~/img/p02.jpg" alt="">
            <h4>传真机</h4>
            <p>· 热敏纸传真机</p>
            <p>· 普通纸传真机</p>
        </li>
        <li>
            <img src="~/img/p03.jpg" alt="">
            <h4>投影机</h4>
            <p>· 家庭影院型</p>
            <p>· 短焦型</p>
            <p>· 教育会议型</p>
            <p>· 主流工程型</p>
            <p>· 专业剧院型</p>
        </li>
        <li style="margin: 0">
            <img src="~/img/p04.jpg" alt="">
            <h4>复印机</h4>
            <p>· A3黑白复印机</p>
            <p>· A3彩色复印机</p>
        </li>
    </ul>
</div>
<div class="qi">
    <div class="ri">
        <h2>联系我们</h2>
        <p>
            公司地址：南京市玄武区珠江路688号1-01幢280室<br>
            公司邮箱：njmcxsm@126.com<br>
            联系人：王先生 18105180604
        </p>
        <p>
            <img src="~/img/map.jpg" alt="">
        </p>
    </div>
    <div class="le">
        <h2>@Html.ActionLink("详情", "About", "Device")公司简介</h2>
        <b>
            <img src="~/img/pic01.jpg" alt=""></b>
        <p>
            &nbsp;&nbsp;&nbsp;&nbsp;南京名炽行数码科技有限公司主要经营现代办公设备、品牌电脑、会议设备、办公文具等高科技产品，并提供专业化的维修售后服务，是一家产品、技术、服务配备齐全的专业化公司。<br>
            &nbsp;&nbsp;&nbsp;&nbsp;本公司经营的办公产品实行多样化经营，一切以客户需求为中心。专业的办公应用方案设计；专业的方案实施；专业的售后服务。客户需求及行业专业性双元素的结合，为客户轻松、高效、经济的实现各类办公应用。<br>
            &nbsp;&nbsp;&nbsp;&nbsp;南京名炽行数码科技有限公司将与各企事业单位融为一体，成为大家的IT部、咨询部、网络部……
        </p>
    </div>
</div>

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Device/Search.cshtml
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>产品搜索</h2>
<div style="clear: both;"></div>

<div class="result">搜索结果：<b>L30墨仓式打印机</b></div>
<div class="printer">
    <div>
        <p style="font-size: 16px; color: #666; font-weight: bold;">喷墨打印机</p>
        <p class="epson">爱普生 L301 墨仓式打印机</p>
        <a href="" class="check">查看详情</a>
    </div>
    <div>
        <p style="font-size: 16px; color: #666; font-weight: bold;">喷墨打印机</p>
        <p class="epson">爱普生 L301 墨仓式打印机</p>
        <a href="" class="check">查看详情</a>
    </div>
    <div style="border: 0">
        <p style="font-size: 16px; color: #666; font-weight: bold;">喷墨打印机</p>
        <p class="epson">爱普生 L301 墨仓式打印机</p>
        <a href="" class="check">查看详情</a>
    </div>
</div>

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Device/SearchPartial.cshtml
@using (Html.BeginForm("Search", "Device"))
{
    @Html.TextBox("cont1ent")
    <button type="submit">搜 索</button>
}

Device/DeviceMvcWeb/DeviceMvcWeb/DeviceMvcWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh-cn" dir="ltr">
<head>
    <title>南京名炽行数码科技有限公司</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="@Url.Content("../img/style.css")"  type="text/css" />
</head>
<body>
    <div class="head-box">
        <div class="head">
            <div class="search">
                @Html.Partial("SearchPartial")
            </div>
            <cite>
                @Html.ActionLink("首页", "Index", "Device", new { @class = ViewBag.IndexClass })
                @Html.ActionLink("产品介绍", "Product", "Device", new { @class = ViewBag.ProductClass })
                @Html.ActionLink("联系我们", "About", "Device", new { @class = ViewBag.AboutClass })
            </cite>
            <a href="@Url.Action("Index")">
                <img src="~/img/logo.png" alt=""></a>
        </div>
    </div>
    <div class="banner-box"></div>
    <div class="arc">
        @RenderBody()
    </div>
    <div class="foot-box">
        <div class="foot">
            <ul>
                <li>
                    <p>南京名炽行数码科技有限公司</p>
                    <p>玄武区珠江路688号1-01幢280室</p>
                    <p>njmcxsm@126.com</p>
                    <p>王先生 18105180604</p>
                </li>
                <li>
                    <p style="font-weight: bold; font-size: 14px;">业务类型</p>
                    <p>现代化办公室设备</p>
                    <p>品牌电脑</p>
                    <p>会议设备</p>
                    <p>办公文具</p>
                </li>
                <li>
                    <p style="font-weight: bold; font-size: 14px;">产品类型</p>
                    <p>打印机</p>
                    <p>传真机</p>
                    <p>复印机</p>
                    <p>投影机</p>
                    <p>碎纸机</p>
                </li>
                <li>
                    <p style="font-weight: bold; font-size: 14px; line-height: 30px;">关于我们</p>
                    <p>@Html.ActionLink("联系我们", "About", "Device")</p>
                </li>
            </ul>
            <p class="co">copyright©2014  all rights reserved</p>
        </div>
    </div>


</body>
</html>